(require 'color-theme)
(color-theme-initialize)
;; http://edward.oconnor.cx/config/elisp/color-theme-hober2.el (wget) 
(load-file (concat config-dir "/vendor/twilight-emacs/color-theme-twilight.el"))
(color-theme-twilight)
